### ISSUE TITLE
Installation process alert

### ISSUE THREAD

**Issue by LorenzoFabris** [NAnand-TUD/parablade#10]
Hi everyone, 
after having completed all the requirements listed on the main page, I downloaded PARABLADE code and launched RunMe.sh. 
The following alert is printed out even after modifications to the .bashrc file. 
Someone has already experienced this behavior?

![Schermata da 2022-05-02 20-09-18](https://user-images.githubusercontent.com/96534491/166319150-1cbeb775-ee4e-443c-94e9-6fd7c00fb956.png)

**LAPTOP INFO**
_OS: Ubuntu 20.04
gcc version: 9.4.0
pip 20.0.2_

**Comment by NAnand-TUD** [comment]
This is because the default python path mentioned in the top of executables are #!/usr/local/bin or equivalent. Since you are using anaconda that location is different. Hence to use the Executables as recommended you should change the headers in all files present in folder bin. Cheers, Nitish

**Comment by NAnand-TUD** [comment]
That would be strange, please check on the internet I am sure it is a general python problem and something related to ParaBlade itself.

Thanks,
Ntiish
