### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by ndkazu** [NAnand-TUD/parablade#4]
Hello,
Could you make an explanation for the use of optimization.py please:
- What is the Objective function, and where is it calculated?
- What files are required? (it seems that the matched profile file and the original profile config file are needed...can you confirm and/or complete please)
Thank you in advance.
Kazu

**Comment by NAnand-TUD** [comment]
Hey Kazu,

Thanks for your comments. There is a test case called Gradient Validation in the test case folder. Maybe you can test that first... Obviously, if you have any question I would be happy to support you. Yes Matchedcoordinate and matchedparametrization files are required for optimization. We are also working on a more modular version of Optimization code.. I hope we will be able to share that on GitHub soon... 

I hope this information was useful. If you have follow up questions, please do not hesitate.

-Nitish

**Comment by ndkazu** [comment]
Hello Nitish,
I am trying to run the Optimization without success.
I am working On Anaconda in windows 10, SU2 version 7.01 is installed in windows, so I am loading the environment variables in OptimizeBlade.Py as shown below:

os.environ["SU2_RUN"] ="F:/SU2/SU2-v7.1.1-win64/bin"
SU=os.environ["SU2_RUN"]
sys.path.append(SU)

For some reason, I cannot install msmpi, so SU2 only runs in serial. I tried to modify the value of MPI_COMMAND from "mpirun -n %i %s %s" to "%s %s", and every call of self.MPI_COMMAND% (for example: self.MPI_COMMAND%(self.N_CORES,'SU2_CFD_AD',self.ADJ_CONFIG)  --> self.MPI_COMMAND%('SU2_CFD_AD',self.ADJ_CONFIG)), but it did not work.
I need help to make it work on Anaconda/Windows with a serial version of SU2.

thanks in advance.

Kazunobu

**Comment by NAnand-TUD** [comment]
Hey Kazunobu,

We never tested the case in Windows but only in Unix and MacOS. We were eventually able to make ParaBlade work in Windows but without Optimisation routine. Hence, I would not really recommend using Windows for SU2 at least. Regarding the MPI Runs you will have to change them individually yourself. Serial code for optimisation does not make much sense to be very honest, hence, such arrangements were not considered when coding.

If you happen to find solution for Windows, let me know. We will be happy to look at it and amend the code accordingly.

Thanks,
Nitish

**Comment by ndkazu** [comment]
Hello Nitish,
I am almost done modifying the Optimization code to make it work with Windows 10/Anaconda and SU2 7.01. Unfortunately, I am not familiar with SU2, and modifying the config file and the mesh file (which are both coming from an older version of SU2) is not leading me anywhere.
My question: once you have your 2D profile using Parablade, how do you generate the mesh for SU2? what can I use to visualize the file "*.geometry"?

**Comment by NAnand-TUD** [comment]
Hey Kazu,

*.geometry is a an input for inhouse code. Alternative, you can extend it to work for gmsh. We are currently developing this feature and will push it when we have it. If you are using SU2 V7 you have to remove SEND_RECEIVE marker from the mesh and do appropriate changes in Config file. This test case was made for SU2 V5 and has not been tested for V7. Things might have changed there.

Thanks,
Nitish
