### ISSUE TITLE
Feature request: Construction of blade flow domain (blade passage)

### ISSUE THREAD

**Issue by o4fr** [NAnand-TUD/parablade#6]
Hi, first off all, thank you for providing this piece of work to the open source community. 

I would like to suggest the following feature:
Construction of blade flow domain (blade passage) i.e. upper, lower, hub and shroud boundary for the flow domain around a singe blade. This would be very useful in order to analyze blade performance in various types of numerical software tools.

I will gladly help if I can, but I only posses general python skills and limited understanding of blade parameterization algorithms.

**Comment by NAnand-TUD** [comment]
Hello !

Thanks for your suggestions.

The feature is already developed in our private repository. Unfortunately, this has not been released yet as it is in major work in progress. The new release will come with better-structured code and the ability to couple several advanced optimization methods. 

We hope to release this soon.

Thanks for your interest in ParaBlade.

-Nitish and Roberto
